In [1]:
import torch
x=torch.ones((10,8))
print(x)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [5]:
y=torch.rand((8,8))
print(y)

tensor([[0.5580, 0.5876, 0.5446, 0.1984, 0.8800, 0.2198, 0.4478, 0.9230],
        [0.8322, 0.9325, 0.8420, 0.8931, 0.8639, 0.2548, 0.8647, 0.4915],
        [0.8207, 0.7215, 0.9897, 0.9303, 0.0346, 0.2672, 0.5700, 0.8832],
        [0.0086, 0.0327, 0.7725, 0.1630, 0.2914, 0.0327, 0.5227, 0.5639],
        [0.9180, 0.5152, 0.1536, 0.4509, 0.6964, 0.0224, 0.8796, 0.5469],
        [0.8190, 0.7550, 0.3246, 0.2488, 0.6821, 0.7449, 0.5950, 0.8500],
        [0.8428, 0.6622, 0.8559, 0.6954, 0.4822, 0.2504, 0.0657, 0.0345],
        [0.0544, 0.6621, 0.1727, 0.1123, 0.8337, 0.3081, 0.3959, 0.9626]])


In [6]:
if torch.cuda.is_available():
    x=x.cuda()
    y=y.cuda()
    z=x.mm(y)
    print(z)

tensor([[4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555],
        [4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555],
        [4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555],
        [4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555],
        [4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555],
        [4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555],
        [4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555],
        [4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555],
        [4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555],
        [4.8535, 4.8688, 4.6557, 3.6922, 4.7644, 2.1002, 4.3416, 5.2555]],
       device='cuda:0')
