In [4]:
import subprocess
try:
    subprocess.check_output('nvidia-smi')
    print('Nvidia GPU detected!')
    subprocess.run('nvidia-smi')
except Exception:
    print('No Nvidia GPU in system!')
    exit()
    

Nvidia GPU detected!
Mon Feb 12 16:11:40 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.34                 Driver Version: 546.26       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    On  | 00000000:01:00.0  On |                  N/A |
| N/A   37C    P8              13W /  80W |    692MiB /  6144MiB |     12%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----

In [5]:
import torch
x=torch.ones((10,8))
print(x)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [6]:
y=torch.rand((8,8))
print(y)

tensor([[0.3363, 0.4457, 0.2896, 0.0941, 0.9279, 0.1751, 0.4762, 0.5259],
        [0.0122, 0.0138, 0.4626, 0.4876, 0.7030, 0.1784, 0.1291, 0.1086],
        [0.6812, 0.8439, 0.9313, 0.2081, 0.0840, 0.2670, 0.0780, 0.2973],
        [0.9467, 0.2990, 0.4144, 0.3396, 0.2648, 0.4542, 0.1137, 0.0211],
        [0.1147, 0.1427, 0.9751, 0.1021, 0.7793, 0.7219, 0.9906, 0.5879],
        [0.8149, 0.3864, 0.9039, 0.8874, 0.3593, 0.6393, 0.4342, 0.2430],
        [0.6803, 0.9087, 0.9196, 0.4212, 0.9040, 0.7711, 0.5136, 0.8038],
        [0.5618, 0.4951, 0.5579, 0.2915, 0.0535, 0.1423, 0.8318, 0.8602]])


In [7]:
if torch.cuda.is_available():
    x=x.cuda()
    y=y.cuda()
    z=x.mm(y)
    print(z)

tensor([[4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479],
        [4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479],
        [4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479],
        [4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479],
        [4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479],
        [4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479],
        [4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479],
        [4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479],
        [4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479],
        [4.1481, 3.5352, 5.4546, 2.8316, 4.0758, 3.3491, 3.5672, 3.4479]],
       device='cuda:0')
